-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sof_users
(
    id serial NOT NULL,
    name character varying(20) NOT NULL,
    password character varying(20) NOT NULL,
    CONSTRAINT user_id_pk PRIMARY KEY (id),
    CONSTRAINT name_must_be_unique UNIQUE (name),
    CONSTRAINT id_must_be_unique UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.question
(
    id serial NOT NULL,
    user_id integer,
    title text,
    description text,
    created timestamp without time zone,
    CONSTRAINT question_id_pk PRIMARY KEY (id),
    CONSTRAINT id_must_be_unique UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.answers
(
    id serial NOT NULL,
    question_id integer,
    user_id integer,
    description text,
    created timestamp without time zone,
    accepted boolean,
    CONSTRAINT answer_id_pk PRIMARY KEY (id),
    CONSTRAINT id_must_be_unique UNIQUE (id)
);

ALTER TABLE IF EXISTS public.question
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id)
    REFERENCES public.sof_users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.answers
    ADD CONSTRAINT question_id_fk FOREIGN KEY (question_id)
    REFERENCES public.question (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.answers
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id)
    REFERENCES public.sof_users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;

END;